name: Validate

on:
  workflow_call:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Run prettier fix
        run: npm run prettier:fix

  eslint:
    name: Run eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run eslint
